name: Test

on:
  push:
    branches: [master, develop]
  pull_request:
    branches: [master, develop]

jobs:
  build:
    runs-on: ubuntu-20.04
    permissions:
      contents: write
      actions: write
      attestations: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Docker Build Test
        run: docker buildx build --load --tag test:test --file ./Dockerfile ./

      - name: Version
        if: github.event_name != 'pull_request'
        uses: cycjimmy/semantic-release-action@v3
        with:
          semantic_version: 17.4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
